name: Publish

on:
  push:
    branches: [main]
    paths:
      - crds.yaml
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Generate schemas
        run: |
          uv python install
          uv sync --locked --all-extras --dev
          uv run src/main.py
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "fix(schemas): generate schemas"
          file_pattern: "schemas/"
